name: PushToAzure
  
on:
  # push 到 main 分支時會觸發
   push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

    - name: sync to azure
      run: |
        git remote add azure  https:/<PAT>@dev.azure.com/DerekProject/EBookGenerator/_git/EBookGenerator
        git branch -D main
        git checkout -b main
        git push -u azure main --force
